spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.5:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s #超时时间
      repositories:
        enabled: true